consensus/beacon/consensus.go, consensus/clique/clique.go, consensus/consensus.go, consensus/ethash/consensus.go, consensus/parlia/parlia.go, consensus/parlia/snapshot.go, core/txpool/bundlepool/bundlepool.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, core/types/bid.go, core/types/bundle.go, eth/api_backend.go, eth/backend.go, eth/ethconfig/config.go, eth/handler.go, ethclient/ethclient.go, go.mod, internal/ethapi/api_bundle.go, internal/ethapi/api_issue.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go, les/api_backend.go, light/txpool.go, miner/bidder.go, miner/miner.go, miner/worker.go, miner/worker_builder.go
feat: builder framework for BEP-322
=> feat: builder framework

core/txpool/bundlepool/bundlepool.go, core/txpool/errors.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/api_backend.go, eth/handler.go, internal/ethapi/api_bundle.go, internal/ethapi/backend.go, miner/miner.go
=> feat: implement eth_sendBundle and eth_bundlePrice

core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, core/types/bundle.go, miner/bundle_cache.go, miner/worker.go, miner/worker_builder.go
=> feat: add bundle cache

consensus/parlia/parlia.go, core/txpool/bundlepool/bundlepool.go, core/txpool/subpool.go, core/txpool/txpool.go, core/types/bid.go, core/types/bundle.go, eth/handler.go, internal/ethapi/api_issue.go, miner/bidder.go, miner/bundle_cache.go, miner/miner.go, miner/worker.go, miner/worker_builder.go
feat: mining bundles and transactions
* ...
=> feat: fill bundles and transactions 

consensus/parlia/parlia.go, core/types/bid.go, core/types/bundle.go, eth/api_backend.go, internal/ethapi/api_issue.go, internal/ethapi/backend.go, les/api_backend.go, miner/bidder.go, miner/miner.go, miner/worker.go, miner/worker_builder.go
=> chores: update the logic of calculating bundle profit and block reward

miner/bidder.go, miner/miner.go, miner/worker.go, miner/worker_builder.go
=> fix: bugs when mining

eth/api_backend.go
fix: a nil pointer when query bundle price
* ...
=> fix: a nil pointer when query bundle price

README.md
=> chore: builder readme

miner/worker.go, miner/worker_builder.go
=> fix: bug in profit calculation (#35)

core/types/bundle.go, miner/bundle_cache.go, miner/miner.go, miner/worker_builder.go
fix: return exact result when send bundle
* ...
=> fix: return exact result when send bundle

core/types/bundle_gasless.go, eth/api_backend.go, ethclient/ethclient.go, internal/ethapi/api_bundle.go, internal/ethapi/backend.go, miner/miner.go, miner/worker_builder.go
=> feat: add api to simulate gasless bundle

core/types/bundle_gasless.go, miner/worker_builder.go
=> feat: explicitly return invalid txs when simulate gasless bundle

core/txpool/bundlepool/bundlepool.go, core/txpool/subpool.go, core/txpool/txpool.go, core/types/bundle.go, eth/api_backend.go, eth/backend.go, ethclient/ethclient.go, internal/ethapi/api_bundle.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go
implementation for BEP https://github.com/bnb-chain/BEPs/pull/460
=> feat: add api to query bundles by block range

core/types/bundle.go, core/types/transaction.go, internal/ethapi/api_bundle.go, miner/worker_builder.go
=> feat: support droppingTxHashes when sendBundle

core/txpool/bundlepool/bundlepool.go
=> fix: nil map in bundlepool 

core/txpool/bundlepool/bundlepool.go
=> fix: concurrent map read in bundlepool

cmd/devp2p/internal/ethtest/conn.go, consensus/beacon/consensus.go, consensus/misc/eip4844/eip4844.go, core/blockchain_diff_test.go, core/state/state_object.go, core/txpool/blobpool/blobpool_test.go, core/txpool/errors.go, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, core/txpool/validation.go, core/types/transaction.go, eth/gasprice/gasprice_test.go, eth/protocols/eth/handler_test.go, eth/tracers/internal/tracetest/supply_test.go, graphql/graphql_test.go, internal/ethapi/api.go, p2p/discover/common.go, p2p/discover/table_reval.go, p2p/discover/v5_udp.go, params/config.go, tests/run-evm-tests.sh, triedb/pathdb/database_test.go
=> feat: upstream bsc develop branch

miner/worker_builder.go
=> fix: reduce gas limit for builder block(revert accidentally delete)

CHANGELOG.md, cmd/jsutils/getchainstatus.js, miner/worker.go, params/config.go, version/version.go
=> Upstream 1.5.6

.nancy-ignore, CHANGELOG.md, cmd/geth/chaincmd.go, cmd/geth/config.go, cmd/geth/main.go, cmd/jsutils/getchainstatus.js, cmd/utils/flags.go, consensus/misc/eip4844/eip4844.go, core/genesis.go, core/rawdb/prunedfreezer.go, core/types/bid.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, internal/ethapi/api.go, metrics/exp/exp.go, metrics/label.go, metrics/prometheus/collector.go, miner/bid_simulator.go, miner/bidder.go, miner/miner_mev.go, miner/minerconfig/config.go, miner/worker.go, params/config.go, params/forks/forks.go, version/version.go
upstream: merge upstream v1.5.11 tag
code merge
NA
* v1.5.11 changes
=> upstream: merge upstream v1.5.11 tag

cmd/geth/config.go, cmd/jsutils/getchainstatus.js, consensus/parlia/parlia.go, consensus/parlia/ramanujanfork.go, consensus/parlia/snapshot.go, core/blockchain.go, core/headerchain.go, core/state_processor.go, eth/protocols/eth/protocol.go, eth/state_accessor.go, eth/tracers/api.go, internal/ethapi/api.go, miner/bid_simulator.go, miner/bidder.go, miner/miner.go, miner/worker.go, params/network_params.go, params/protocol_params.go, rpc/json-rpc-api.md
=> upstream: merge upstream develop branch
