bnb-chain/bsc-builder

- Makefile
- README.builder.md
- consensus/consensus.go
- consensus/parlia/parlia.go
- core/txpool/bundlepool/bundlepool.go
- core/txpool/bundlepool/config.go
- core/txpool/subpool.go
- core/txpool/txpool.go
- core/types/bundle.go
- eth/api_backend.go
- eth/backend.go
- eth/ethconfig/config.go
- ethclient/ethclient.go
- internal/ethapi/api_bundle.go
- internal/ethapi/api_mev.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- miner/bidder.go
- miner/bundle_cache.go
- miner/miner.go
- miner/miner_mev.go
- miner/miner_test.go
- miner/validatorclient/validatorclient.go
- miner/worker.go
- miner/worker_builder.go
- miner/worker_test.go
This pr is to implement the BEP322 builder-api.
This project represents a minimal implementation of the protocol and is provided as is. We make no guarantees regarding its functionality or security.
See also: https://github.com/bnb-chain/BEPs/pull/322
* implement BEP322 builder-api
> builder: implement BEP322 builder-api

- miner/bidder.go
- miner/bundle_cache.go
- miner/worker_builder.go
> fix: index out of range

- miner/bidder.go
- miner/worker.go
feat: call mev_params before send bid
* ...
> feat: call mev_params before send bid

- internal/ethapi/api_bundle.go
- miner/bidder.go
> fix: NPE and wrong profit

- core/blockchain.go
- miner/worker_builder.go
This ps is to fix a concurrent map write issue in `simulateBundles` of `work_builder`
* add write lock for simulation results map
* remove check of `bc.NoTries()` to prevent snapsync
> fix: concurrent map write issue

- core/blockchain.go
- eth/handler.go
- eth/sync.go
This pr is to fix an issue that the node will wrongly switch sync mode from full sync to snap sync
* ...
> fix: wrongly switch sync mode

- miner/miner.go
This pr is to fix a bug in miner module
* add EIP4844 part when preparing env in `SimulateBundle`
> fix: add missing part when preparing env in `SimulateBundle`

- internal/ethapi/api_bundle.go
feat: sendBundle return bundle hash
* ...
> feat: sendBundle return bundle hash

- core/txpool/bundlepool/bundlepool.go
This pr is to fix a typo.
* Change from `p.mu.RUnlock()` to `p.mu.RLock()`
> fix: typo in `BundlePool.AllBundles`

- miner/bidder.go
- miner/worker.go
This pr is to add `reconnectLoop` for mev validators
To make the bidder reconnect to offline validators automatically.
* add `reconnectLoop` for mev validators
> feat: add `reconnectLoop` for mev validators

- ethclient/ethclient.go
> feat: ethclient of bundle

- CHANGELOG.md
- core/blockchain.go
- core/forkchoice.go
- core/genesis.go
- core/headerchain.go
- core/rawdb/chain_iterator.go
- core/rawdb/database.go
- core/types/bid.go
- eth/api_backend.go
- eth/backend.go
- eth/fetcher/block_fetcher.go
- eth/handler_eth_test.go
- eth/sync_test.go
- ethclient/ethclient.go
- internal/ethapi/api_mev.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args.go
- internal/ethapi/transaction_args_test.go
- miner/miner_mev.go
- params/version.go
- triedb/pathdb/difflayer.go
- triedb/pathdb/disklayer.go
- triedb/pathdb/layertree.go
- triedb/pathdb/metrics.go
Merge the v1.4.10 upstream code
* ...
> merge upstream v1.4.10 code

- miner/worker.go
- miner/worker_builder.go
1. Currently, the worker uses GasPrice to calculate profit when committing a transaction. This method has issues when calculating EIP1559-type transactions. Refer to https://github.com/bnb-chain/bsc-builder/blob/b0668a82c7dbe20dae3b7874ffce4aba9e57ccd9/core/state_transition.go#L464 and use EffectiveGasTip to calculate the transaction fee.
2. When calculating blob-type transactions, the blob fee needs to be included.
> fix: bug in profit calculation

- core/types/bundle_gasless.go
- eth/api_backend.go
- ethclient/ethclient.go
- internal/ethapi/api_bundle.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- miner/miner.go
- miner/worker_builder.go
fix: only take non-mempool tx to calculate bundle price
In current implementation, when a builder receive a bundle, it will simulate all txs within the bundle. Bundle price = sum( gas price * gas used ) /sum(gas used ) , ensure bundle price > = 1 gwei. It seems not a good solution. Consider the following example:
There is a public mempool tx with 100 gwei, gas usage 21,000 and its a simple transfer tx. A malicious actor can submit a 0 gas price tx to bundle it up with the public mempool tx, this tx has 0 gwei gas price, it can involve very complex smart contract calls and it has a gas usage of 1,000,000.
In that case, it will be (10021000+01000000)/(21000+1000000)=2.05 gwei. This means this bundle can be included by builders and land on chain.
However, the malicious actor is essentially a …
> fix: only take non-mempool tx to calculate bundle price

- core/txpool/bundlepool/bundlepool.go
- core/types/bundle_gasless.go
- internal/ethapi/api_bundle.go
- miner/worker_builder.go
> fix: skip incorrect tx in simulate gasless bundle

- core/txpool/bundlepool/bundlepool.go
> fix: deadlock when add bundle into bundlepool

- miner/bidder.go
- miner/worker_builder.go
> fix: unrevertible tx hashes in bidArgs

- CHANGELOG.md
- cmd/geth/main.go
- core/blockchain.go
- core/forkchoice.go
- core/rawdb/prunedfreezer.go
- core/systemcontracts/upgrade.go
- core/systemcontracts/upgrade_test.go
- core/types/blob_sidecar.go
- eth/api_backend.go
- ethclient/ethclient.go
- go.mod
- go.sum
- internal/debug/flags.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- params/config.go
- params/version.go
> feat: merge with upstream v1.4.14

- miner/bidder.go
- miner/worker.go
> feat: logging packing duration

- core/block_validator.go
- miner/bidder.go
- miner/miner.go
- miner/worker.go
- miner/worker_builder.go
> feat: set block gas limit by config

- miner/miner.go
> feat: bundle simulation based on real inturn header

- miner/worker_builder.go
> fix: using snapshot instead of state copy

- miner/worker_builder.go
> fix: using snapshot insead of state copy

- core/block_validator.go
- miner/miner.go
- miner/worker.go
- miner/worker_builder.go
Builder block need to reduce gas limit for MEV performance, but if we directly change the gas limit in header, it would influence many unit test such as `TestWaitDeployed`, the test chain could not be work normally. So only set gas limit before fill transactions for builder block and reset it as the original value after filling done.
* ...
> fix: temporarily reduce gaslimit when fill txs for builder block

- ethclient/simulated/backend_test.go
- ethclient/simulated/rollback_test.go
- miner/bidder.go
- miner/worker.go
In the   commitBlobTransaction   function, the presence of   blobSidecar   in   env.txs   will cause the   ValidateBody   function to fail. This failure, in turn, will have a negative impact on the rollback test.
* ...
> fix: unit case of TestTransactionRollbackBehavior

- core/txpool/bundlepool/bundlepool.go
According to pprof on heap as below pictures from left to right, there are a lot of new memory assigned when sendBundle,    The program keeps holding this memory without freeing it.
Further analysis of the code, every time a new block comes out, only `p.bundles` has been cleared, not `bundleheap`, `bundleheap` would keep large amount of depracated bundles. So we also cleanup the bundlehea at this time.
* ...
> fix: oom in bundlepool
